market:
  init_price_usd: 60000
  init_sigma: 0.03
  adv_usd: 18000000000
  depth_score: 0.7
impact:
  Y_buy: 0.65
  Y_sell: 0.75
  permanent_phi_buy: 0.3
  permanent_phi_sell: 0.28
  temp_decay_tau_days: 2.5
  temp_decay_lambda: 1.1
  otc_visible_fraction: 0.35
exogenous:
  etf_flow_csv: data/flows/etf_flows_sample.csv
  auctions_csv: null
  stochastic_flow_bps: 3.0
adoption:
  model: bass
  bass:
    p: 0.015
    q: 0.38
    m: 24
  threshold:
    default_theta: 0.5
    theta_std: 0.07
    alpha_momentum: 0.18
    alpha_liquidity: 0.12
    alpha_peer: 0.3
    policy_penalty: 0.12
supply:
  lost_btc: 2900000
  miner_sell_frac: 0.32
policy_us:
  start_day: 0
  usd_per_day: 1200000000
  max_frac_adv: 0.06
  venue_mix:
    otc: 0.75
    cex: 0.25
  slippage_budget_bps: 35
  smart_pacing: true
  sell_rules:
    enabled: false
    take_profit_bands: [130000, 200000, 280000]
    tranche_fraction: 0.25
    time_lock_days: 20
countries:
  country_csv: data/countries/country_list.csv
  graph_csv: data/countries/country_graph.csv
  reserves_fraction_on_adopt: 0.06
objective:
  debt_baseline_usd: 37450000000000
  horizon_days: 1825
  seed: 99
  residual_vol: 0.015


